[package]
name = "osmo-bindings-test"
version = "0.4.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Multitest (and other test helpers) support for Osmosis-specific contracts"
repository = "https://github.com/confio/osmosis-bindings"
homepage = "https://osmosis.zone"
license = "Apache-2.0"

[dependencies]
osmo-bindings = { version = "0.4.0", path = "../bindings" }
cosmwasm-std = { version = "1.0.0-beta6" }
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cw-multi-test = { version = "0.13.0" }
cw-storage-plus = { version = "0.13.0" }
anyhow = { version = "1" }
thiserror = { version = "1.0.21" }
