[package]
name = "token-bindings-test"
version = "0.8.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Multitest (and other test helpers) support for Osmosis-specific contracts"
repository = "https://github.com/confio/osmosis-bindings"
homepage = "https://osmosis.zone"
license = "Apache-2.0"

[dependencies]
itertools = "0.10"
token-bindings = { version = "0.8.0", path = "../bindings" }
cosmwasm-std = "1.1"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
cw-multi-test = { git = "https://github.com/0xArbi/cw-multi-test", branch = "arb/supply" }
cw-storage-plus = "0.15"
anyhow = "1"
thiserror = "1.0"
