[package]
name = "osmo-bindings"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Bindings for CustomMsg and CustomQuery for the Osmosis blockchain"
repository = "https://github.com/confio/osmosis-bindings"
homepage = "https://osmosis.zone"
license = "Apache-2.0"

[dependencies]
base64 = "0.13"
cosmwasm-std = { version = "1.0.0-beta6" }
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta6" }
hex-literal = "0.3.1"
